# Generated by Django 3.0.7 on 2020-06-13 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 11, 39, 48, 755236)),
        ),
    ]
